### ISSUE TITLE
cannot run the demo in my local pc

### ISSUE THREAD

**Issue by omer815** [coryjthompson/WebPushDemo#1]
i am tying to run the project in my laptop anf i get alot of error related to the core references 
i tried to do some work but i find it very difficult
can you help me?

**Comment by omer815** [comment]
![image](https://user-images.githubusercontent.com/26647650/39961286-7d22aeb8-563b-11e8-8fb4-d6b277296aa5.png)

**Comment by coryjthompson** [comment]
Hey - looks like you just need to restore nuget packages.

Thanks
-- 
Cory Thompson

**Comment by mhlm71** [comment]
I have the same problem, How can I restore NuGet package, After that how should I use this library in my project which is Asp.net Web Form?

**Comment by coryjthompson** [comment]
dotnet restore 

You should be following the documentation at:
https://github.com/web-push-libs/web-push-csharp

Thanks

**Comment by mhlm71** [comment]
Eventually I had to upgrade Visual Studio to topmost version and everything worked fine. Moreover I had to change parts of the code to become compatible with ASP.Net WebForm.

**Comment by marpinello** [comment]
I have the same problem. Does this project was abandoned ??
